## LINEAR ALGEBRA TASK

In [2]:
import numpy as np

In [4]:
house = np.array([2,3,4])
print(house)
print(house.shape)

[2 3 4]
(3,)


### Matrix Operations

In [7]:
A = np.array([[2, -1],[0, 3]])
print(A.shape)
B = np.array([
    [1, 2],
    [-3, 4]
])
print(B.shape)

(2, 2)
(2, 2)


In [13]:
print("Addition of two matrices A and B is : ")
print(A + B)

Addition of two matrices A and B is : 
[[ 3  1]
 [-3  7]]


In [12]:
print("The Dot Product of A and B is: ")
print(A @ B)

The Dot Product of A and B is: 
[[ 5  0]
 [-9 12]]


In [16]:
print(" The expression \"3*A - 2*B\"")
print(3 * A - 2 * B)

 The expression "3*A - 2*B"
[[ 4 -7]
 [ 6  1]]


##  Determinants and Inverses  

In [18]:
import numpy.linalg as LA

In [24]:
print("Determinants of A is:")
A = np.array([
    [2, -1],
    [0, 3]
])
print(A)
LA.det(A)

Determinants of A is:
[[ 2 -1]
 [ 0  3]]


np.float64(6.0)

Determinant of A is 6 . Hence, it is a non-singular matrix and it is invertible.


# A^-1

In [36]:
print("Inverse of the matrix A :")
print(A)
print( LA.inv(A))

Inverse of the matrix A :
[[ 2 -1]
 [ 0  3]]
[[0.5        0.16666667]
 [0.         0.33333333]]


## Eigen Value and Eigen Vectors

In [29]:
C = np.array([
    [4, 1],
    [-2, 1]
])
print(C.shape)

(2, 2)


In [32]:
eigenvalues, eigenvectors = np.linalg.eig(C)
print("Matrix C:")
print(A)
print("\nEigenvalue :")
print(eigenvalues[0])
print("\n Eigenvector:")
print(eigenvectors[:, 0])

Matrix C:
[[ 2 -1]
 [ 0  3]]

Eigenvalue :
3.0

 Eigenvector:
[ 0.70710678 -0.70710678]


In [38]:
X = np.array([
    [4, 1.5, 100],
    [6, 2.0, 150]
])

y = np.array([20, 30])

In [40]:
beta = np.linalg.pinv(X) @ y

In [46]:
car3 = np.array([8, 3.0, 200])
price = car3 @ beta 
print(" Car 3:")
print(car3)
print("Price of the car 3 is ",price)

 Car 3:
[  8.   3. 200.]
Price of the car 3 is  40.00000000000002
